export const dataGuest = {
  data: [
    {
      active: true,
      account: "GA001",
      status: "VIP",
      stay: 2,
      guest_name: "Giacomo Guillzoni",
      first_name: "Giacomo",
      last_name: "Guillzoni",
      title: "Mr.",
      nationality: "Germany",
      tel: "094750954",
      mobile_phone: "089657558",
    },
    {
      active: true,
      account: "GA002",
      status: "VIP",
      stay: 7,
      guest_name: "Marco Liberty",
      first_name: "Marco",
      last_name: "Liberty",
      title: "Mr.",
      nationality: "Germany",
      tel: "094750954",
      mobile_phone: "089657558",
    },
    {
      active: true,
      account: "GA003",
      status: "VIP",
      stay: 10,
      guest_name: "Mariah Sam",
      first_name: "Mariah",
      last_name: "Sam",
      title: "Mrs.",
      nationality: "Germany",
      tel: "094750954",
      mobile_phone: "089657558",
    },
    {
      active: true,
      account: "GA004",
      status: "Normal",
      stay: 2,
      guest_name: "Valerie Rush",
      first_name: "Valerie",
      last_name: "Rush",
      title: "Ms.",
      nationality: "Germany",
      tel: "094750954",
      mobile_phone: "089657558",
    },
    {
      active: true,
      account: "GA005",
      status: "Normal",
      stay: 2,
      guest_name: "Damian Liberty",
      first_name: "Damian",
      last_name: "Liberty",
      title: "Mr.",
      nationality: "Germany",
      tel: "094750954",
      mobile_phone: "089657558",
    },
    {
      active: true,
      account: "GA006",
      status: "Normal",
      stay: 2,
      guest_name: "Sandra Blum",
      first_name: "Sandra",
      last_name: "Blum",
      title: "Ms.",
      nationality: "Germany",
      tel: "094750954",
      mobile_phone: "089657558",
    },
  ],
  pagging: {
    limit_data: 10,
    total_data: 2,
    start_paging: 1,
    end_paging: 1,
    prev_jump: 0,
    prev: 0,
    next: 0,
    next_jump: 0,
  },
  permission: {
    view: true,
    add: true,
    edit: true,
    delete: true,
    active: true,
    approve: true,
    reject: true,
  },
  code: 200,
  message: "Success",

  table: [
    {
      label: "Active",
      key: "active",
      type: "checkbox",
      is_search: false,
    },
    {
      label: "Account",
      key: "account",
      type: "text",
      is_link: true,
      is_search: true,
    },
    {
      label: "Status",
      key: "status",
      type: "text",
      is_search: true,
    },
    {
      label: "Stay",
      key: "stay",
      type: "number",
      is_search: true,
    },
    {
      label: "Guest Name",
      key: "guest_name",
      type: "text",
      is_search: true,
    },
    {
      label: "Last Name",
      key: "last_name",
      type: "text",
      is_search: true,
    },
    {
      label: "First Name",
      key: "first_name",
      type: "text",
      is_search: true,
    },
    {
      label: "Title",
      key: "title",
      type: "text",
      is_search: true,
    },
    {
      label: "Nationality",
      key: "nationality",
      type: "text",
      is_search: true,
    },
    {
      label: "Tel",
      key: "tel",
      type: "text",
      is_search: true,
    },
    {
      label: "Mobile Phone",
      key: "mobile_phone",
      type: "text",
      is_search: true,
    },
  ],
};
